version: '3.1'

services:
 db:
  image: postgres
  container_name: postgres
  restart: always
  ports:
   - 5432:5432
  volumes:
   - ./postgresDB:/var/lib/postgresql/data
  environment:
   POSTGRES_PASSWORD: 9uxXYpq5yTxGK8U2rZ
   POSTGRES_DB: uek109
 web:
  image: node
  container_name: site
  restart: always
  user: "node"
  working_dir: /home/node/app
  environment:
   NODE_ENV: production
   DB_HOST: db
   DB_USER: postgres
   DB_PASS: 9uxXYpq5yTxGK8U2rZ
   DB_PORT: 5432
   DB_DATABASE: uek109
  volumes:
   - ./:/home/node/app
  ports:
  - 80:3000
  command: "npm start"
